// vue3-vite/src/views/Detail.vue
<script setup>
import { useRoute } from 'vue-router';
import { ref, onMounted } from 'vue';
import Image from '@/components/Image.vue';

const apiUrl = import.meta.env.VITE_API_DETAIL_URL;
const dog = ref({});
const route = useRoute();

onMounted(async () => {
    const response = await fetch(`${apiUrl}${route.params.dogId}`);
    if (response.ok) {
        dog.value = await response.json();
    }
});
</script>
<template>
    <main>
        <router-link to="/">zurück</router-link>
        <Image :src="dog.url" :alt="dog.id" />
        <router-link to="/">zurück</router-link>
    </main>
</template>

// react-vite/src/routes/Detail.jsx
import Image from '../components/Image';
import { Link, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';

function Detail() {
    const { dogId } = useParams();
    const [dog, setDog] = useState({});

    useEffect(async () => {
        const response = await fetch(`${import.meta.env.VITE_API_DETAIL_URL}${dogId}`);
        if (response.ok) {
            setDog(await response.json());
        }
    }, [dogId]);

    return <main>
        <Link to="/">zurück</Link>
        <Image 
            src={dog.url}
            alt={dog.id}
        />
        <Link to="/">zurück</Link>
    </main>;
};

export default Detail;
