// vue3-vite/src/views/Home.vue
<script setup>
import { ref, onMounted } from 'vue';
import Image from '@/components/Image.vue'

const apiUrl = import.meta.env.VITE_API_URL;
const dogs = ref([]);

onMounted(() => {
    if (window.sessionStorage.getItem('dogs')) {
        dogs.value = JSON.parse(window.sessionStorage.getItem('dogs'));
        return;
    }
    fetchDogs();
});

async function fetchDogs() {
    const response = await fetch(apiUrl);
    if (response.ok) {
        dogs.value = await response.json();
        window.sessionStorage.setItem('dogs', JSON.stringify(dogs.value));
    }
}
</script>

<template>
    <div>
        <button
            class="button"
            @click="fetchDogs"
        >
            refresh dog list
        </button>
        <ul class="ul">
            <li 
                v-for="dog in dogs"
                :key="dog.id"
                class="li"
            >
                <router-link :to="`/dog/${dog.id}`">
                    <Image
                        :src="dog.url"
                        :alt="dog.id"
                        cover
                    />
                </router-link>
            </li>
        </ul>
    </div>
</template>

<style scoped>

.ul {
    list-style: none;
    display: flex;
    flex-wrap: wrap;
    margin: 0;
    padding: 0;
}
  
.li {
    width: 100%;
}

.button {
    background-color: var(--header-bg-color);
    color: var(--header-text-color);
    border: 2px solid var(--accent-color);
    border-radius: .25rem;
    padding: .2rem .3rem;
    margin: .2rem;
    font-weight: 700;
}

  
@media screen and (min-width: 640px) {
    .li {
        width: 50%;
    }
}
  
@media screen and (min-width: 768px) {
    .li {
        width: 33%;
    }
}
</style>

// react-vite/src/routes/Home.jsx
import { useEffect, useState } from 'react';
import Image from '../components/Image';
import './Home.css';
import { Link } from 'react-router-dom';

function Home() {

    const [dogs, setDogs] = useState([]);

    async function fetchDogs() {
        const response = await fetch(import.meta.env.VITE_API_URL);
        if (response.ok) {
            setDogs(await response.json());
        }
    }

    useEffect(() => {
        if (dogs.length === 0) {
            fetchDogs();
        }
    }, []);

    return <main>
        <button className="button" onClick={fetchDogs}>
            refresh dog list
        </button>
        <ul className="ul">
            {dogs.map(dog => <li className="li">
                <Link to={`/dog/${dog.id}`}>
                    <Image
                        cover
                        src={dog.url}
                        alt={dog.id}
                    />
                </Link>
            </li>)}
        </ul>
    </main>;
};

export default Home;
