// react/src/routes/Detail.js
import { Component } from 'react';
import { Link, withRouter } from 'react-router-dom';
import Image from '../components/Image';

class Detail extends Component {
    constructor(props) {
        super(props);
        this.dogId = this.props.match.params.dogId;
        this.state = { dog: {} };
    }
    componentDidMount() {
        this.fetchDog(this.dogId, this.props.apiUrl);
    }

    fetchDog(dogId, apiUrl = 'https://api.thedogapi.com/v1/images/') {
        fetch(`${apiUrl}${dogId}`)
            .then(response => response.json())
            .then(data => this.setState({ dog: data }));
    }

    render() {
        return <main>
                <h1>Dog #{this.state.dog.id}</h1>
                <Link to="/">zurück</Link>
                <Image
                    src={this.state.dog.url}
                    alt={this.state.dog.id}
                />
                <Link to="/">zurück</Link>
            </main>
    }
}

export default withRouter(Detail);

// vue3-vite/src/views/Detail.vue
<script setup>
import { useRoute } from 'vue-router';
import { ref, onMounted } from 'vue';
import Image from '@/components/Image.vue';

const apiUrl = 'https://api.thedogapi.com/v1/images/';
const dog = ref({});
const route = useRoute();

onMounted(async () => {
    const response = await fetch(`${apiUrl}${route.params.dogId}`);
    if (response.ok) {
        dog.value = await response.json();
    }
});
</script>
<template>
    <main>
        <router-link to="/">zurück</router-link>
        <Image :src="dog.url" :alt="dog.id" />
        <router-link to="/">zurück</router-link>
    </main>
</template>
