// vue3-cli/src/views/Detail.vue
<template>
    <main>
        <h1>Dog #{{$route.params.dogId}}</h1>
        <router-link to="/">zurück</router-link>
            <Image
                :src="dog.url"
                :alt="dog.id"
            />
        <router-link to="/">zurück</router-link>
    </main>
</template>

<script>
import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router'
import Image from '@/components/Image.vue';
import { fetchDog } from '@/dogs';
export default {
    name: 'Detail',
    components: {
        Image,
    },
    setup() {
        const dog = ref({});
        const route = useRoute()

        onMounted(async() => {
            dog.value = await fetchDog(route.params.dogId);
        });

        return {
            dog,
        };
    },
}
</script>

// react-fn/src/routes/Detail.js
import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';

import Image from '../components/Image';
function Detail(props) {
    const { dogId } = useParams();

    const [dog, setDog] = useState({});

    useEffect(() => {
        fetchDog();
    }, [dogId]);

    async function fetchDog() {
        const response = await fetch(`${props.apiUrl}${dogId}`);

        if (response.ok) {
            setDog(await response.json());
        }
    }

    return <main>
        <h1>Dog #{dog.id}</h1>
        <Link to="/">zurück</Link>
        <Image
            src={dog.url}
            alt={dog.id}
        />
        <Link to="/">zurück</Link>
    </main>;
}

export default Detail;
