// react-class/src/components/Image.js
import { Component } from 'react';
import './Image.css';

class Image extends Component {
    render() {
        return <picture>
            <img className={`img ${this.props.cover ? 'img--cover' : ''}`}
                src={this.props.src}
                alt={this.props.alt}
            />
        </picture>;
    }
}

export default Image;

// vue3-cli/src/components/Image.vue
<template>
    <picture>
        <img
            class="img"
            :class="{'img--cover' : cover}"
            :src="src"
            :alt="alt"
        >
    </picture>
</template>

<script>
export default {
    name: 'Image',
    props: {
        cover: {
            type: Boolean,
            default: false
        },
        src: {
            type: String,
            default: null,
        },
        alt: {
            type: String,
            default: null,
        },
    },
};
</script>

<style scoped>
.img {
    max-width: 100%;
    height: auto;
}

.img--cover {
    height: 100%;
    object-fit: cover;
    object-position: center;
}
</style>
