// svelte-kit/src/lib/Image.svelte
<script lang="ts">
    export let cover:Boolean = false;
    export let src:string = null;
    export let alt:string = null;
</script>

<picture>
    <img
        class="img"
        class:img--cover={cover}
        {src}
        {alt}
    >
</picture>

<style>
.img {
    max-width: 100%;
    height: auto;
}

.img--cover {
    height: 100%;
    object-fit: cover;
    object-position: center;
}
</style>

// nuxt3/components/Image.vue
<template>
    <picture>
        <img
            :class="{
                'img' : true,
                'img--cover': cover
            }"
            :src="src"
            :alt="alt"
        >
    </picture>
</template>

<script setup>
const props = defineProps({
    cover: Boolean,
    src: String,
    alt: String,
});
</script>

<style scoped>
.img {
    max-width: 100%;
    height: auto;
}

.img--cover {
    height: 100%;
    object-fit: cover;
    object-position: center;
}
</style>
